# Generated by Django 4.2.17 on 2025-02-20 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0086_issueversion_alter_teampage_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='is_workspace_wide',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='WebhookProject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_webhooks', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_projects', to='db.webhook')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_webhook_projects', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Webhook Project',
                'verbose_name_plural': 'Webhook Projects',
                'db_table': 'webhook_projects',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='webhookproject',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('webhook', 'project'), name='webhook_project_unique_webhook_project_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='webhookproject',
            unique_together={('webhook', 'project', 'deleted_at')},
        ),
    ]
