# Generated by Django 4.2.17 on 2025-03-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0087_webhook_is_workspace_wide_webhookproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='team_strength',
            field=models.FloatField(default=1.0, verbose_name='Team Strength'),
        ),
    ]
