# Generated by Django 4.2.17 on 2025-03-06 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0087_webhook_is_workspace_wide_webhookproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_cycle_length',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Week'), (2, '2 Weeks'), (3, '3 Weeks'), (4, '4 Weeks')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='project',
            name='initial_velocity',
            field=models.FloatField(default=10.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='project',
            name='velocity_strategy',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Cycle'), (2, '2 Cycles'), (3, '3 Cycles'), (4, '4 Cycles')], default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
