# Generated by Django 4.2.17 on 2025-03-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0088_cycle_team_strength'),
        ('db', '0088_project_default_cycle_length_and_more'),
    ]

    operations = [
    ]
