# Generated by Django 4.2.17 on 2025-03-06 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0089_merge_team_strength_and_velocity'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_velocity',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
