apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: plane-redis
  name: plane-redis
spec:
  type: ClusterIP
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    io.kompose.service: plane-redis
